### ISSUE TITLE
Unsupported date format in recent sample

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/gromstole#74]
```python
Traceback (most recent call last):
  File "scripts/aggregate-mapped.py", line 39, in <module>
    coldate = parse_date(row['coldate'])
  File "scripts/aggregate-mapped.py", line 17, in parse_date
    raise ValueError(f"No supported format detected for date string {dt}")
ValueError: No supported format detected for date string 25/10/22
```

**Comment by ArtPoon** [comment]
Added `%d/%m/%y` to list of formats to attempt, but this is getting ridiculous
