### ISSUE TITLE
Missing dependency after freyja update

### ISSUE THREAD

**Issue by GopiGugan** [PoonLab/gromstole#93]
Freyja was recently updated:

`freyja                                 1.5.0-pyhdfd78af_0 --> 1.5.1-pyhdfd78af_0`

Resulting in the following error when running `freyja demix`:

```python
Traceback (most recent call last):
  File "lib/python3.10/site-packages/pandas/compat/_optional.py", line 141, in import_optional_dependency
    module = importlib.import_module(name)
  File "lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pyarrow'
```

**Comment by GopiGugan** [comment]
`pyarrow` was added as a dependency: https://github.com/andersen-lab/Freyja/compare/v1.5.0...v1.5.1

There may be multiple additional requirements `docs/requirements.txt`

**Comment by GopiGugan** [comment]
```python3
demixing
module 'cvxpy' has no attribute 'CLARABEL'
Error: Demixing step failed. Returning empty data output
```

**Comment by GopiGugan** [comment]
Resolved after upgrading `cvxpy`

Need to switch from using `usher_barcodes.csv` to `lineage_mutations.json` - https://github.com/andersen-lab/Freyja/commit/27bcfbaa22a3d012d05e3a274cd332f8ce36117f
